=== bjimenezm02/2324_LMSGI_Diario/TrabajoiDiario/Tema5/DTD/Ej08v1.dtd
<!ELEMENT programme     (degree, year, results)>
<!ELEMENT degree        (#PCDATA)>
<!ELEMENT year          (#PCDATA)>
<!ELEMENT results       (distinction*, merit*, pass*, fail*)>
<!ELEMENT distinction   (name*)>
<!ELEMENT merit         (name*)>
<!ELEMENT pass          (name*)>
<!ELEMENT fail          (name*)>
<!ELEMENT name          (#PCDATA)*>

=== bjimenezm02/2324_LMSGI_Diario/TrabajoiDiario/Tema5/DTD/Ej08v3.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE programme SYSTEM "Ej08v1.dtd">

<programme>
    <degree></degree>
    <year></year>
    <results>
        <distinction>
            <name></name>
        </distinction>
        <merit>
            <name></name>
        </merit>
        <pass>
            <name></name>
        </pass>
    </results>
</programme>
