=== bjimenezm02/2324_LMSGI_Diario/TrabajoiDiario/Tema5/DTD/Ej09.dtd
<!ELEMENT partidos (partido)+>
<!ELEMENT partido (jornada+, equipo_local, equipo_visitante, goles*)>
<!ELEMENT jornada (#PCDATA)>    
<!ELEMENT equipo_local (nombre, entrenador, jugadores)>
<!ATTLIST equipo_local id ID #REQUIRED> 
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT entrenador (#PCDATA)>
<!ELEMENT jugadores (jugador)+>
<!ELEMENT jugador (nombre, posicion, n_tarjetas)>
<!ATTLIST jugador n_camiseta ID #REQUIRED>
<!ELEMENT posicion (#PCDATA)>
<!ELEMENT n_tarjetas (rojas*, amarillas*)*>
<!ELEMENT rojas (#PCDATA)>  
<!ELEMENT amarillas (#PCDATA)>
<!ELEMENT equipo_visitante (nombre, entrenador, jugadores+)>
<!ATTLIST equipo_visitante id ID #REQUIRED>
<!ELEMENT goles (gol)*>
<!ELEMENT gol (id_equipo, penalty*)>
<!ATTLIST gol nombre IDREF #REQUIRED>
<!ELEMENT id_equipo (IDREF)>
<!ELEMENT penalty (#PCDATA)>

=== bjimenezm02/2324_LMSGI_Diario/TrabajoiDiario/Tema5/DTD/Ej09.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE partidos SYSTEM "Ej09.dtd" [

]>

<partidos>
    <partido>
        <jornada>  </jornada>
        <equipo_local id = "">
            <nombre>  </nombre>
            <entrenador>  </entrenador>
            <jugadores>
                <jugador n_camiseta = " ">
                    <nombre>  </nombre>
                    <posicion>  </posicion>
                    <n_tarjetas>
                        <amarillas></amarillas>
                        <rojas></rojas>
                    </n_tarjetas>
                </jugador>
                <jugador n_camiseta = " ">
                    <nombre>  </nombre>
                    <posicion>  </posicion>
                    <n_tarjetas>
                        <amarillas>  </amarillas>
                        <rojas>  </rojas>
                    </n_tarjetas>
                </jugador>
                <jugador n_camiseta = " ">
                    <nombre>  </nombre>
                    <posicion>  </posicion>
                    <n_tarjetas>
                        <amarillas>  </amarillas>
                    </n_tarjetas>
                </jugador>
                <jugador n_camiseta = " ">
                    <nombre>  </nombre>
                    <posicion>  </posicion>
                    <n_tarjetas>
                        <rojas>  </rojas>
                    </n_tarjetas>
                </jugador>
                <jugador n_camiseta = " ">
                    <nombre>  </nombre>
                    <posicion>  </posicion>
                    <n_tarjetas>
                        <amarillas>  </amarillas>
                        <rojas>  </rojas>
                    </n_tarjetas>
                </jugador>
                <jugador n_camiseta = " ">
                    <nombre>  </nombre>
                    <posicion>  </posicion>
                    <n_tarjetas>
                        <amarillas>  </amarillas>
                        <rojas>  </rojas>
                    </n_tarjetas>
                </jugador>
                <jugador n_camiseta = " ">
                    <nombre>  </nombre>
                    <posicion>  </posicion>
                    <n_tarjetas>
                        <amarillas>  </amarillas>
                        <rojas>  </rojas>
                    </n_tarjetas>
                </jugador>
                <jugador n_camiseta = " ">
                    <nombre>  </nombre>
                    <posicion>  </posicion>
                    <n_tarjetas>
                        <amarillas>  </amarillas>
                        <rojas>  </rojas>
                    </n_tarjetas>
                </jugador>
                <jugador n_camiseta = " ">
                    <nombre>  </nombre>
                    <posicion>  </posicion>
                    <n_tarjetas>
                        <amarillas>  </amarillas>
                        <rojas>  </rojas>
                    </n_tarjetas>
                </jugador>
                <jugador n_camiseta = " ">
                    <nombre>  </nombre>
                    <posicion>  </posicion>
                    <n_tarjetas>
                        <amarillas>  </amarillas>
                        <rojas>  </rojas>
                    </n_tarjetas>
                </jugador>
                <jugador n_camiseta = " ">
                    <nombre>  </nombre>
                    <posicion>  </posicion>
                    <n_tarjetas>
                        <amarillas>  </amarillas>
                        <rojas>  </rojas>
                    </n_tarjetas>
                </jugador>
            </jugadores>
        </equipo_local>
        <equipo_visitante id = "">
            <nombre>  </nombre>
            <entrenador>  </entrenador>
            <jugadores>
                <jugador n_camiseta = " ">
                    <nombre>  </nombre>
                    <posicion>  </posicion>
                    <n_tarjetas>
                        <amarillas>  </amarillas>
                        <rojas>  </rojas>
                    </n_tarjetas>
                </jugador>
                <jugador n_camiseta = " ">
                    <nombre>  </nombre>
                    <posicion>  </posicion>
                    <n_tarjetas>
                        <amarillas>  </amarillas>
                        <rojas>  </rojas>
                    </n_tarjetas>
                </jugador>
                <jugador n_camiseta = " ">
                    <nombre>  </nombre>
                    <posicion>  </posicion>
                    <n_tarjetas>
                        <amarillas>  </amarillas>
                        <rojas>  </rojas>
                    </n_tarjetas>
                </jugador>
                <jugador n_camiseta = " ">
                    <nombre>  </nombre>
                    <posicion>  </posicion>
                    <n_tarjetas>
                        <amarillas>  </amarillas>
                        <rojas>  </rojas>
                    </n_tarjetas>
                </jugador>
                <jugador n_camiseta = " ">
                    <nombre>  </nombre>
                    <posicion>  </posicion>
                    <n_tarjetas>
                        <amarillas>  </amarillas>
                        <rojas>  </rojas>
                    </n_tarjetas>
                </jugador>
                <jugador n_camiseta = " ">
                    <nombre>  </nombre>
                    <posicion>  </posicion>
                    <n_tarjetas>
                        <amarillas>  </amarillas>
                        <rojas>  </rojas>
                    </n_tarjetas>
                </jugador>
                <jugador n_camiseta = " ">
                    <nombre>  </nombre>
                    <posicion>  </posicion>
                    <n_tarjetas>
                        <amarillas>  </amarillas>
                        <rojas>  </rojas>
                    </n_tarjetas>
                </jugador>
                <jugador n_camiseta = " ">
                    <nombre>  </nombre>
                    <posicion>  </posicion>
                    <n_tarjetas>
                        <amarillas>  </amarillas>
                        <rojas>  </rojas>
                    </n_tarjetas>
                </jugador>
                <jugador n_camiseta = " ">
                    <nombre>  </nombre>
                    <posicion>  </posicion>
                    <n_tarjetas>
                        <amarillas>  </amarillas>
                        <rojas>  </rojas>
                    </n_tarjetas>
                </jugador>
                <jugador n_camiseta = " ">
                    <nombre>  </nombre>
                    <posicion>  </posicion>
                    <n_tarjetas>
                        <amarillas>  </amarillas>
                        <rojas>  </rojas>
                    </n_tarjetas>
                </jugador>
                <jugador n_camiseta = " ">
                    <nombre>  </nombre>
                    <posicion>  </posicion>
                    <n_tarjetas>
                        <amarillas>  </amarillas>
                        <rojas>  </rojas>
                    </n_tarjetas>
                </jugador>
            </jugadores>
        </equipo_visitante>
        <goles>
            <gol nombre = "">
                <id_equipo>   </id_equipo>
                <penalty>  </penalty>
            </gol>
        </goles>
    </partido>
</partidos>
